Fix iocp_stubs.c(...): error C2036: 'void *': unknown size
Arithmetic on void pointers is a GCC extension

http://gcc.gnu.org/onlinedocs/gcc-4.8.0/gcc/Pointer-Arith.html

This patch fixes the C build with MSVC which is stricter.

Signed-off-by: David Scott <dave@recoil.org>